body:

    - type: passwordBox
      attributes:
          name: api_key
          label: "OpenRouter API Key:"
          description: "API key for OpenRouter - it is recommended to set your OPENROUTER_API_KEY environment variable key instead"

    - type: input
      attributes:
          name: default_model
          label: "Default AI Model:"
          defaultValue: "deepseek/deepseek-chat:free"
          description: "Select the AI model to use for queries"

    - type: input
      attributes:
          name: delimiter
          label: "Prompt Delimiter:"
          description: "Symbol that indicates when to send the prompt"
          defaultValue: "||"